In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier #model used for classification
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#we don't use standard scaler because it checks the array of features in the cluster which has 5 values
iris=load_iris()
iris = load_iris()

x = iris.data
y = iris.target


df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y

print("First five rows of the data set")
print(df.head())
#it default accepts 5 values

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
# the train should be 80 or 75 % and test should be 20 or 25%
k=5
# specifie the number of neighbour
knn=KNeighborsClassifier(n_neighbors=k)
#function(argument)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
#used to predict the valuees from dataset
print("\nModel Evaluation")
print("----------------")
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))
#accuracy score,confusion matrix,classification report are  the evaluation metrix
new_flower = np.array([[5.1, 3.5, 1.4, 0.2]])
#itt checks the features from the array in the cluster

prediction = knn.predict(new_flower)
#it is used to predict the the flower
print("\nNew Flower Prediction")
print("---------------------")
print("Input:", new_flower)
print("Predicted Species:", iris.target_names[prediction][0])

First five rows of the data set
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  

Model Evaluation
----------------
Accuracy: 1.0

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg  